version: "3.8"

services:
  api:
    build: .
    container_name: node-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: crud_db
      DB_USER: postgres
      DB_PASS: postgres
    volumes:
      - .:/app

  consumer:
    build: .
    container_name: rabbit-consumer
    command: ["node", "rabbit/consumer.js"]
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: crud_db
      DB_USER: postgres
      DB_PASS: postgres
    volumes:
      - .:/app

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crud_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
